### ISSUE TITLE
Crystal/oscillator size and polarity marking

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-footprints#296] opened 2018-01-23 17:23 UTC
Polarity markings aren't in accordance with IPC: https://github.com/KiCad/Crystals.pretty/issues/23 and https://github.com/KiCad/Oscillators.pretty/issues/6. Note that most (all?) are script-generated with more info at the first link.

https://github.com/KiCad/Crystals.pretty/issues/24 mentions a possible seems to point out a mismatch between a package name and the package size.

**Comment by poeschlr** [comment] 2018-01-24 00:12
This is a duplicate of https://github.com/KiCad/kicad-footprints/issues/156 and https://github.com/KiCad/kicad-footprints/issues/155. I assume it can be closed?

**Comment by evanshultz** [comment] 2018-01-29 16:57
I closed #156 because it didn't have any new info. But the other two have some overlap, but still some unique info. I'll add the above to #155 and close this one.

**Closed** 2018-01-29 16:58 UTC
Labels: help wanted
