### ISSUE TITLE
TSOT-23-6 - 3D model wrong link

### ISSUE THREAD

**Issue by DecadoPL** [KiCad/kicad-footprints#1582] opened 2019-05-07 12:32 UTC
PCB library for footprint TSOT-23-6 doesn't display 3D model due to wrong link.

It is:
${KISYS3DMOD}/Package_TO_SOT_SMD.3dshapes/TSOT-23-6.wrl
But should be(according to file names):
${KISYS3DMOD}/Package_TO_SOT_SMD.3dshapes/TSOT-23-6MK06A.wrl

I'm new(1 week) KiCad user and don't want to change it by myself in repo.  Would be nice if You could fix it.

**Comment by evanshultz** [comment] 2019-05-07 14:59
Thanks for taking the time to notice this and report it.

The issue is actually the 3D model name being wrong. This is a standard package so the MK06A suffix does not need to be included. (I guess it came from a datasheet like https://www.adrirobot.it/datasheet/integrati/pdf/LM2736Y.pdf?)

I'm closing this PR now and have created a new issue at https://github.com/KiCad/kicad-packages3D/issues/546.

**Closed by evanshultz** 2019-05-07 14:59 UTC
